on:
  pull_request_target:

jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ github.actor }}'
  c:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - run: gh pr merge ${{ github.event.pull_request.number }}
